//
//
//Service should have method to do following.
//-> Addition
//-> Substraction
//-> Multiplication
//-> Division

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: calculator_def.proto

package calculator_def

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 float64 `protobuf:"fixed64,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 float64 `protobuf:"fixed64,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *NumPair) Reset() {
	*x = NumPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumPair) ProtoMessage() {}

func (x *NumPair) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumPair.ProtoReflect.Descriptor instead.
func (*NumPair) Descriptor() ([]byte, []int) {
	return file_calculator_def_proto_rawDescGZIP(), []int{0}
}

func (x *NumPair) GetNum1() float64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *NumPair) GetNum2() float64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_calculator_def_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_def_proto protoreflect.FileDescriptor

var file_calculator_def_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x22, 0x31, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xf4, 0x01, 0x0a, 0x0a,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x38, 0x0a, 0x03, 0x61, 0x64,
	0x64, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64,
	0x65, 0x66, 0x2e, 0x4e, 0x75, 0x6d, 0x50, 0x61, 0x69, 0x72, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x12, 0x17, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x4e, 0x75, 0x6d,
	0x50, 0x61, 0x69, 0x72, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x03, 0x64, 0x69, 0x76, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x4e, 0x75, 0x6d, 0x50, 0x61, 0x69, 0x72, 0x1a, 0x16,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03, 0x6d, 0x75, 0x6c, 0x12,
	0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66,
	0x2e, 0x4e, 0x75, 0x6d, 0x50, 0x61, 0x69, 0x72, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x64, 0x65, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_def_proto_rawDescOnce sync.Once
	file_calculator_def_proto_rawDescData = file_calculator_def_proto_rawDesc
)

func file_calculator_def_proto_rawDescGZIP() []byte {
	file_calculator_def_proto_rawDescOnce.Do(func() {
		file_calculator_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_def_proto_rawDescData)
	})
	return file_calculator_def_proto_rawDescData
}

var file_calculator_def_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_def_proto_goTypes = []any{
	(*NumPair)(nil), // 0: calculator_def.NumPair
	(*Result)(nil),  // 1: calculator_def.Result
}
var file_calculator_def_proto_depIdxs = []int32{
	0, // 0: calculator_def.Calculator.add:input_type -> calculator_def.NumPair
	0, // 1: calculator_def.Calculator.sub:input_type -> calculator_def.NumPair
	0, // 2: calculator_def.Calculator.div:input_type -> calculator_def.NumPair
	0, // 3: calculator_def.Calculator.mul:input_type -> calculator_def.NumPair
	1, // 4: calculator_def.Calculator.add:output_type -> calculator_def.Result
	1, // 5: calculator_def.Calculator.sub:output_type -> calculator_def.Result
	1, // 6: calculator_def.Calculator.div:output_type -> calculator_def.Result
	1, // 7: calculator_def.Calculator.mul:output_type -> calculator_def.Result
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_def_proto_init() }
func file_calculator_def_proto_init() {
	if File_calculator_def_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculator_def_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NumPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_def_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_def_proto_goTypes,
		DependencyIndexes: file_calculator_def_proto_depIdxs,
		MessageInfos:      file_calculator_def_proto_msgTypes,
	}.Build()
	File_calculator_def_proto = out.File
	file_calculator_def_proto_rawDesc = nil
	file_calculator_def_proto_goTypes = nil
	file_calculator_def_proto_depIdxs = nil
}
